GET http://localhost:9000 HTTP/1.1

### Success
POST http://localhost:9000/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.ru",
    "password": "test"
}

### Error: Invalind login or password
POST http://localhost:9000/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.ru",
    "password": "123456"
}

### get token
POST http://localhost:9000/token HTTP/1.1
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ItCa0YPQutC60L4g0JzQuNGF0LDQuNC7IiwiZW1haWwiOiJ0ZXN0QHRlc3QucnUiLCJpYXQiOjE3MDg4NzU4ODEsImV4cCI6MTcwODk2MjI4MX0.Fy9wmM6gJmMwLnFwsBtgEfarQZEMnP4MYYI_KkRhvZc"
}

### revoke token
POST http://localhost:9000/revoketoken HTTP/1.1
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ItCa0YPQutC60L4g0JzQuNGF0LDQuNC7IiwiZW1haWwiOiJ0ZXN0QHRlc3QucnUiLCJpYXQiOjE3MDg4Nzg4MDYsImV4cCI6MTcwODk2NTIwNn0.C_bfd7YylFdnL7QzKOoIlXBnjwlGapLB7qlpFmThBJg"
}

### get products
GET http://localhost:9000/products HTTP/1.1
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikt1a2tvIE1pY2hhaWwiLCJlbWFpbCI6InRlc3RAdGVzdC5ydSIsImlhdCI6MTcwOTY1NDAzOSwiZXhwIjoxNzA5NjU0OTM5fQ.hfw_hFqFirYgfbWIAMKVG56ezcsd0SY7zhPwLQ07b-0
content-type: application/json

### get product by id
GET http://localhost:9000/product/2 HTTP/1.1
content-type: application/json


### add to Cart
POST http://localhost:9000/addToCart HTTP/1.1
content-type: application/json

{
    "userId": "1",
    "productId": "2",
    "quantity": 123
}

### fetch cart by userId
GET http://localhost:9000/fetchcart/1 HTTP/1.1
content-type: application/json

### remove from cart
DELETE http://localhost:9000/removebyid/1/2 HTTP/1.1
content-type: application/json

### update quantity
PATCH http://localhost:9000/updatequantity HTTP/1.1
content-type: application/json

{
    "userId": "1",
    "productId": "1",
    "quantity": 444
}

### clear cart
DELETE http://localhost:9000/clearcart/1 HTTP/1.1
content-type: application/json