export const kTestProducts = [
    {
      id: '1',
      imageUrl: 'assets/products/bruschetta-plate.jpg',
      title: 'Bruschetta plate',
      description: 'Lorem ipsum',
      price: 15,
      availableQuantity: 5,
    },
    {
      id: '2',
      imageUrl: 'assets/products/mozzarella-plate.jpg',
      title: 'Mozzarella plate',
      description: 'Lorem ipsum',
      price: 13,
      availableQuantity: 5,
    },
    {
      id: '3',
      imageUrl: 'assets/products/pasta-plate.jpg',
      title: 'Pasta plate',
      description: 'Lorem ipsum',
      price: 17,
      availableQuantity: 5,
    },
    {
      id: '4',
      imageUrl: 'assets/products/piggy-blue.jpg',
      title: 'Piggy Bank Blue',
      description: 'Lorem ipsum',
      price: 12,
      availableQuantity: 5,
    },
    {
      id: '5',
      imageUrl: 'assets/products/piggy-green.jpg',
      title: 'Piggy Bank Green',
      description: 'Lorem ipsum',
      price: 12,
      availableQuantity: 10,
    },
    {
      id: '6',
      imageUrl: 'assets/products/piggy-pink.jpg',
      title: 'Piggy Bank Pink',
      description: 'Lorem ipsum',
      price: 12,
      availableQuantity: 10,
    },
    {
      id: '7',
      imageUrl: 'assets/products/pizza-plate.jpg',
      title: 'Pizza plate',
      description: 'Lorem ipsum',
      price: 18,
      availableQuantity: 10,
    },
    {
      id: '8',
      imageUrl: 'assets/products/plate-and-bowl.jpg',
      title: 'Plate and Bowl',
      description: 'Lorem ipsum',
      price: 21,
      availableQuantity: 10,
    },
    {
      id: '9',
      imageUrl: 'assets/products/salt-pepper-lemon.jpg',
      title: 'Salt and pepper lemon',
      description: 'Lorem ipsum',
      price: 11,
      availableQuantity: 10,
    },
    {
      id: '10',
      imageUrl: 'assets/products/salt-pepper-olives.jpg',
      title: 'Salt and pepper olives',
      description: 'Lorem ipsum',
      price: 11,
      availableQuantity: 10,
    },
    {
      id: '11',
      imageUrl: 'assets/products/snacks-plate.jpg',
      title: 'Snacks plate',
      description: 'Lorem ipsum',
      price: 24,
      availableQuantity: 10,
    },
    {
      id: '12',
      imageUrl: 'assets/products/flowers-plate.jpg',
      title: 'Flowers plate',
      description: 'Lorem ipsum',
      price: 22,
      availableQuantity: 10,
    },
    {
      id: '13',
      imageUrl: 'assets/products/juicer-citrus-fruits.jpg',
      title: 'Juicer for citrus fruits',
      description: 'Lorem ipsum',
      price: 14,
      availableQuantity: 10,
    },
    {
      id: '14',
      imageUrl: 'assets/products/honey-pot.jpg',
      title: 'Honey pot',
      description: 'Lorem ipsum',
      price: 16,
      availableQuantity: 10,
    },
  ];

  export function getProducts() {
    return kTestProducts;
  }